/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is auto-generated by `next dev`/`next build` and should
// not be edited manually. It is checked in here only so the project has a
// complete, working TypeScript setup out of the box.
